### ISSUE TITLE
Trying the refitting code

### ISSUE THREAD

**Issue by alien19** [tim-hilt/vlad#1]
Hello Tim, really appreciate your efforts in the code.
But I have a question concerning trying the *refit* function so, if you have tried it please tell me what is the shape/type of the database used to refit https://github.com/tim-hilt/vlad/blob/47b969b328892c57229b9002456298b776ecd3e4/vlad/vlad.py#L171 also I have doubts about this line in *refit* function https://github.com/tim-hilt/vlad/blob/47b969b328892c57229b9002456298b776ecd3e4/vlad/vlad.py#L180  why to reset the centers values if we will use them as  initials to the new refit.

thanks in advance.

**Comment by tim-hilt** [comment]
To be honest, I think I never really used `refit`, so this issue never really played itself out. You're right in that https://github.com/tim-hilt/vlad/blob/47b969b328892c57229b9002456298b776ecd3e4/vlad/vlad.py#L180 should be deleted, because it doesn't make much sense.

The database `X` should be of the same form of what you were using for the initial fitting.

Keep in mind, that I'm the only one who wrote this code and some time has already passed since I've even worked with Python, let alone this repository.

I hope this was helpful nonetheless! Thanks for showing interest in my work!
